version: '3'
services:
    app:
        image: nginx:latest
        container_name: tester-app
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app/www:/app/www
    php:
        container_name: tester-php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
    mysql:
        container_name: tester-mysql
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root123'
            MYSQL_USER: 'default'
            MYSQL_PASSWORD: 'pass123'
            MYSQL_DATABASE: 'db'
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/start.sql
        # ports:
        #     - 3306:3306